# Generated by Django 5.2.15 on 2026-06-25 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot2', '0016_student_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('cv', 'CV / Rezume'), ('ielts', 'IELTS Sertifikati'), ('certificate', 'Boshqa Sertifikat'), ('diploma', 'Diplom'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='verifications/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Navbatda'), ('processing', 'Tahlil qilinmoqda'), ('done', 'Tayyor'), ('failed', 'Xatolik')], default='pending', max_length=20)),
                ('confidence_level', models.CharField(blank=True, choices=[('green', 'Yashil (ishonchli)'), ('yellow', 'Sariq (shubhali)'), ('red', 'Qizil (past ishonch)')], max_length=10, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('extracted_data', models.JSONField(default=dict)),
                ('flags', models.JSONField(default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('final_decision', models.CharField(choices=[('pending', "Ko'rib chiqilmagan"), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='pending', max_length=10)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_verifications', to='bot2.bot2student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_verification_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'document_type'], name='ai_verifica_student_87852c_idx'), models.Index(fields=['status'], name='ai_verifica_status_a7a0f3_idx'), models.Index(fields=['confidence_level'], name='ai_verifica_confide_80be85_idx'), models.Index(fields=['final_decision'], name='ai_verifica_final_d_d3f23f_idx')],
            },
        ),
    ]
