# Generated by Django 5.2.15 on 2026-06-25 10:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(default='document_verification', max_length=50)),
                ('model_name', models.CharField(choices=[('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash-Lite'), ('gemini-2.5-pro', 'Gemini 2.5 Pro')], default='gemini-2.5-flash', max_length=50)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('thinking_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('success', 'Muvaffaqiyatli'), ('error', 'Xatolik')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='ai_verification.documentverification')),
            ],
            options={
                'db_table': 'ai_usage_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name'], name='ai_usage_lo_model_n_b376e2_idx'), models.Index(fields=['operation'], name='ai_usage_lo_operati_96eb1a_idx'), models.Index(fields=['created_at'], name='ai_usage_lo_created_aa64d8_idx'), models.Index(fields=['status'], name='ai_usage_lo_status_45f32e_idx')],
            },
        ),
    ]
