# Generated by Django 5.2.15 on 2026-06-29 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_verification', '0003_documentverification_source_document'),
        ('bot2', '0018_alter_bot2document_doc_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentverification',
            name='document_type',
            field=models.CharField(choices=[('cv', 'CV / Rezume'), ('ielts', 'IELTS Sertifikati'), ('certificate', 'Boshqa Sertifikat'), ('diploma', 'Diplom'), ('employment', "Ish joyi ma'lumotnomasi"), ('other', 'Boshqa')], default='other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='documentverification',
            index=models.Index(fields=['-created_at'], name='ai_verifica_created_2266c2_idx'),
        ),
    ]
