# Generated by Django 5.2.10 on 2026-01-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_actor_t_d85e51_idx',
            old_name='audit_audit_actor_t_8a43ba_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action_86e815_idx',
            old_name='audit_audit_action_e23ad0_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_entity__335c7b_idx',
            old_name='audit_audit_entity__cc103e_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_created_2c1626_idx',
            old_name='audit_audit_created_4fd726_idx',
        ),
    ]
