# Generated by Django 5.2.10 on 2026-01-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot1', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bot1applicant',
            new_name='bot1_bot1ap_telegra_6f7506_idx',
            old_name='bot1_bot1ap_telegr_6bba15_idx',
        ),
        migrations.RenameIndex(
            model_name='bot1applicant',
            new_name='bot1_bot1ap_telegra_c7eba2_idx',
            old_name='bot1_bot1ap_telegr_f6f4fa_idx',
        ),
    ]
