# Generated by Django 5.2.10 on 2026-01-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_program_metadata_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='catalogitem',
            name='catalog_item_type_code_unique_nonnull',
        ),
        migrations.RenameIndex(
            model_name='catalogitem',
            new_name='catalog_cat_type_477a0d_idx',
            old_name='catalog_cat_type_f9f96b_idx',
        ),
        migrations.RenameIndex(
            model_name='catalogitem',
            new_name='catalog_cat_type_784a05_idx',
            old_name='catalog_cat_type_fafc7c_idx',
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', True), _negated=True), fields=('type', 'code'), name='catalog_item_type_code_unique_nonnull'),
        ),
    ]
