# Generated by Django 5.2.5 on 2026-02-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_catalogitem_catalog_item_type_code_unique_nonnull_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='name_uz',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
