# Generated by Django 5.2.5 on 2026-03-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_multilingual_name_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='catalogitem',
            name='catalog_item_type_code_unique_with_nulls',
        ),
        migrations.RemoveConstraint(
            model_name='catalogitem',
            name='catalog_item_type_code_unique_nonnull',
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('code__isnull', True), _negated=True), models.Q(('code', ''), _negated=True)), fields=('type', 'code'), name='catalog_item_type_code_unique_nonnull'),
        ),
    ]
