# Generated by Django 5.2.5 on 2026-03-03 11:25

from django.db import migrations, models


def drop_constraints_safe(apps, schema_editor):
    """Drop catalog code constraints if they exist (idempotent for any DB state)."""
    conn = schema_editor.connection
    names = [
        "catalog_item_type_code_unique_with_nulls",
        "catalog_item_type_code_unique_nonnull",
    ]
    with conn.cursor() as cursor:
        if conn.vendor == "postgresql":
            for name in names:
                cursor.execute(
                    f"ALTER TABLE catalog_catalogitem DROP CONSTRAINT IF EXISTS {name};"
                )
        # SQLite does not support DROP CONSTRAINT; Django tracks state only.


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_multilingual_name_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_constraints_safe, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='catalogitem',
                    name='catalog_item_type_code_unique_with_nulls',
                ),
                migrations.RemoveConstraint(
                    model_name='catalogitem',
                    name='catalog_item_type_code_unique_nonnull',
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='catalogitem',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(('code__isnull', True), _negated=True),
                    models.Q(('code', ''), _negated=True),
                ),
                fields=('type', 'code'),
                name='catalog_item_type_code_unique_nonnull',
            ),
        ),
    ]
