# Generated by Django 5.2.13 on 2026-06-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_overly_strict_code_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='type',
            field=models.CharField(choices=[('program', 'Program'), ('direction', 'Direction'), ('subject', 'Subject'), ('track', 'Track'), ('region', 'Region'), ('skill', 'Skill'), ('industry', 'Industry'), ('other', 'Other')], max_length=50),
        ),
    ]
