# Generated by Django 5.2.15 on 2026-06-29 05:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_auto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('employment_type', models.CharField(choices=[('full_time', "To'liq stavka"), ('part_time', 'Yarim stavka'), ('internship', 'Amaliyot / Internship'), ('contract', 'Shartnoma'), ('remote', 'Masofaviy')], default='full_time', max_length=20)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='UZS', max_length=10)),
                ('apply_url', models.URLField(blank=True)),
                ('apply_contact', models.CharField(blank=True, max_length=255)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', "E'lon qilingan"), ('closed', 'Yopilgan'), ('archived', 'Arxivlangan')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vacancies', to=settings.AUTH_USER_MODEL)),
                ('direction', models.ForeignKey(blank=True, help_text="Qaysi yo'nalish talabalariga mos (type=direction/program)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies_direction', to='catalog.catalogitem')),
                ('region', models.ForeignKey(blank=True, help_text="type=region bo'lishi kerak", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies_region', to='catalog.catalogitem')),
            ],
            options={
                'db_table': 'vacancies_vacancy',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VacancyChannelPost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Yangi post'), ('edit', 'Tahrirlash'), ('delete', "O'chirish")], default='create', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Navbatda'), ('sent', 'Yuborildi'), ('failed', 'Xatolik'), ('skipped', "O'tkazib yuborildi")], default='pending', max_length=10)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('channel_id', models.CharField(max_length=100)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_posts', to='vacancies.vacancy')),
            ],
            options={
                'db_table': 'vacancies_channel_post',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['status'], name='vacancies_v_status_7f8d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['employment_type'], name='vacancies_v_employm_6a03e0_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['region'], name='vacancies_v_region__91205f_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['direction'], name='vacancies_v_directi_150149_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['published_at'], name='vacancies_v_publish_32bff5_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancychannelpost',
            index=models.Index(fields=['status'], name='vacancies_c_status_840493_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancychannelpost',
            index=models.Index(fields=['vacancy'], name='vacancies_c_vacancy_e098c3_idx'),
        ),
    ]
