# Generated by Django 5.2.15 on 2026-06-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='address',
            field=models.CharField(blank=True, help_text="Ko'cha/bino manzili", max_length=255),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(blank=True, help_text='3-5 yil', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vacancies/'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='schedule',
            field=models.CharField(blank=True, help_text='5/2, 9:00-18:00', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tags',
            field=models.CharField(blank=True, help_text='#python #backend', max_length=255),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_format',
            field=models.CharField(blank=True, choices=[('onsite', 'Ofisda'), ('remote', 'Masofaviy'), ('hybrid', 'Aralash')], help_text='Ish joyi formati: ofisda/masofaviy/aralash', max_length=10),
        ),
        migrations.AddField(
            model_name='vacancychannelpost',
            name='media_type',
            field=models.CharField(choices=[('text', 'Matn'), ('photo', 'Rasm')], default='text', help_text='CREATE da yuborilgan xabar turi (text/photo) — edit/delete uchun kerak', max_length=10),
        ),
    ]
