# Generated by Django 5.2.13 on 2026-06-18 12:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot2', '0010_auto'),
        ('employers', '0001_auto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('access_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm.accesslink')),
            ],
            options={
                'ordering': ('-accessed_at',),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('viewing', 'Viewing'), ('selected', 'Selected'), ('closed', 'Closed')], default='created', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='employers.employer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='accesslink',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_link', to='crm.lead'),
        ),
        migrations.CreateModel(
            name='LeadStudent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_interested', models.BooleanField(default=False)),
                ('forwarded', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_students', to='crm.lead')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bot2.bot2student')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='students',
            field=models.ManyToManyField(related_name='leads', through='crm.LeadStudent', to='bot2.bot2student'),
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('interviewed', 'Interviewed'), ('done', 'Done')], default='pending', max_length=12)),
                ('outcome', models.CharField(blank=True, choices=[('interviewed', 'Interviewed'), ('placed', 'Placed'), ('no_contact', 'No Contact'), ('no_interview', 'No Interview')], max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_send_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_for_staff', models.BooleanField(default=False)),
                ('lead_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='crm.leadstudent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='leadstudent',
            constraint=models.UniqueConstraint(fields=('lead', 'student'), name='uq_lead_student'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='crm_lead_status_2c1bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['employer'], name='crm_lead_employe_b15315_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['next_send_at'], name='crm_followu_next_se_a7f08a_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['stage'], name='crm_followu_stage_e8ce89_idx'),
        ),
    ]
