# Generated by Django 5.2.15 on 2026-06-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstudent',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leadstudent',
            name='ai_summary_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
