# Generated by Django 5.2.15 on 2026-06-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_leadstudent_ai_summary_leadstudent_ai_summary_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstudent',
            name='ai_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
