# Generated by Django 5.2.15 on 2026-07-15 07:53

from django.db import migrations, models
from django.db.models import Count


def dedupe_active_followups(apps, schema_editor):
    """Constraint qo'shishdan oldin dublikat faol follow-uplarni tozalaydi.

    Har bir lead_student uchun eng so'nggi (created_at bo'yicha) faol follow-up
    qoladi; qolganlari DONE deb belgilanadi (o'chirmaymiz — tarix saqlanadi).
    """
    FollowUp = apps.get_model("crm", "FollowUp")
    dupes = (
        FollowUp.objects.exclude(stage="done")
        .values("lead_student_id")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    for row in dupes:
        active = list(
            FollowUp.objects.filter(lead_student_id=row["lead_student_id"])
            .exclude(stage="done")
            .order_by("-created_at")
        )
        for fu in active[1:]:
            fu.stage = "done"
            fu.next_send_at = None
            fu.save(update_fields=["stage", "next_send_at", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_leadstudent_ai_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslink',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.RunPython(dedupe_active_followups, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='followup',
            constraint=models.UniqueConstraint(condition=models.Q(('stage', 'done'), _negated=True), fields=('lead_student',), name='uq_followup_active_per_lead_student'),
        ),
    ]
