# Generated by Django 5.2.10 on 2026-01-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0002_revokedtoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='revokedtoken',
            new_name='authn_revok_expires_e3dca6_idx',
            old_name='authn_revoked_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='revokedtoken',
            new_name='authn_revok_token_t_fdb0ad_idx',
            old_name='authn_revoked_type_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
