# Generated by Django 5.2.10 on 2026-01-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot2', '0002_roster_campaign'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bot2student',
            new_name='bot2_bot2st_student_fc161d_idx',
            old_name='bot2_bot2stu_student_2f52e5_idx',
        ),
        migrations.RenameIndex(
            model_name='bot2student',
            new_name='bot2_bot2st_telegra_e18158_idx',
            old_name='bot2_bot2stu_telegr_6e2a84_idx',
        ),
        migrations.RenameIndex(
            model_name='bot2surveyresponse',
            new_name='bot2_bot2su_survey__2c334a_idx',
            old_name='bot2_bot2sur_survey__319f5a_idx',
        ),
        migrations.RenameIndex(
            model_name='bot2surveyresponse',
            new_name='bot2_bot2su_submitt_f8b20f_idx',
            old_name='bot2_bot2sur_submit_844d3a_idx',
        ),
        migrations.RenameIndex(
            model_name='studentroster',
            new_name='bot2_studen_program_229975_idx',
            old_name='bot2_studen_program_bbea4e_idx',
        ),
        migrations.RenameIndex(
            model_name='studentroster',
            new_name='bot2_studen_course__2f13dd_idx',
            old_name='bot2_studen_course__7600a8_idx',
        ),
        migrations.RenameIndex(
            model_name='studentroster',
            new_name='bot2_studen_is_acti_5ab5f9_idx',
            old_name='bot2_studen_is_activ_8c9b30_idx',
        ),
        migrations.RenameIndex(
            model_name='studentroster',
            new_name='bot2_studen_roster__08e5a6_idx',
            old_name='bot2_roster_campaign_idx',
        ),
    ]
