# Generated by Django 5.2.10 on 2026-01-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot2', '0003_rename_bot2_bot2stu_student_2f52e5_idx_bot2_bot2st_student_fc161d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bot2student',
            name='unique_roster_student_external_id',
        ),
    ]
