# Generated by Django 5.2.10 on 2026-01-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot2', '0004_remove_roster_student_constraint'),
        ('catalog', '0004_remove_catalogitem_catalog_item_type_code_unique_nonnull_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bot2surveyresponse',
            name='unique_roster_campaign',
        ),
        migrations.AddIndex(
            model_name='bot2surveyresponse',
            index=models.Index(fields=['roster', 'survey_campaign'], name='bot2_bot2su_roster__16475f_idx'),
        ),
    ]
