# Generated by Django 5.2.10 on 2026-01-19 05:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot2', '0005_remove_unique_roster_campaign'),
        ('catalog', '0004_remove_catalogitem_catalog_item_type_code_unique_nonnull_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramEnrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_year', models.PositiveSmallIntegerField(help_text='1, 2, 3, or 4', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('student_count', models.PositiveIntegerField(default=0, help_text='Total number of students')),
                ('academic_year', models.CharField(default='2025-2026', help_text='Academic year, e.g. 2025-2026', max_length=20)),
                ('campaign', models.CharField(default='default', help_text='Campaign identifier', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='catalog.catalogitem')),
            ],
            options={
                'ordering': ('program', 'course_year'),
                'indexes': [models.Index(fields=['program', 'course_year'], name='bot2_progra_program_41e010_idx'), models.Index(fields=['academic_year'], name='bot2_progra_academi_8bd528_idx'), models.Index(fields=['campaign'], name='bot2_progra_campaig_931acb_idx'), models.Index(fields=['is_active'], name='bot2_progra_is_acti_f5739a_idx')],
                'unique_together': {('program', 'course_year', 'academic_year', 'campaign')},
            },
        ),
    ]
