# Generated by Django 5.2.5 on 2026-02-17 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot2', '0006_programenrollment'),
        ('catalog', '0004_remove_catalogitem_catalog_item_type_code_unique_nonnull_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bot2surveyresponse',
            name='survey_course_year_between_1_and_4',
        ),
        migrations.AlterField(
            model_name='bot2surveyresponse',
            name='course_year',
            field=models.PositiveSmallIntegerField(help_text='1-4 for active students, 5 for graduated', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='programenrollment',
            name='course_year',
            field=models.PositiveSmallIntegerField(help_text='1-4 for active students, 5 for graduated', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentroster',
            name='course_year',
            field=models.PositiveSmallIntegerField(help_text='1-4 for active students, 5 for graduated', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='bot2surveyresponse',
            constraint=models.CheckConstraint(condition=models.Q(('course_year__gte', 1), ('course_year__lte', 5)), name='survey_course_year_between_1_and_5'),
        ),
    ]
