# Generated by Django 5.2.14 on 2026-05-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot2', '0008_survey_unique_student_campaign'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bot2student',
            name='bot2_bot2st_student_fc161d_idx',
        ),
        migrations.RemoveIndex(
            model_name='bot2student',
            name='bot2_bot2st_telegra_e18158_idx',
        ),
    ]
