# Generated by Django 5.2.13 on 2026-06-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot2', '0009_remove_bot2student_bot2_bot2st_student_fc161d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bot2surveyresponse',
            name='uq_survey_student_campaign',
        ),
        migrations.AddField(
            model_name='bot2student',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot2student',
            name='is_job_seeking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot2student',
            name='language',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=2),
        ),
        migrations.AddField(
            model_name='bot2student',
            name='state',
            field=models.CharField(default='registered', help_text='FSM state persisted to DB; bot resume on restart', max_length=64),
        ),
        migrations.AddField(
            model_name='bot2surveyresponse',
            name='source',
            field=models.CharField(choices=[('survey', 'Survey'), ('lead', 'Lead Placement')], default='survey', max_length=10),
        ),
        migrations.AddField(
            model_name='studentroster',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
