# Generated by Django 5.2.13 on 2026-06-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot2', '0010_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot2surveyresponse',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Bot-supplied dedup key (UUIDv4); prevents double-submit after constraint removal', max_length=64, null=True, unique=True),
        ),
    ]
