# Generated by Django 5.2.15 on 2026-06-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot2', '0012_bot2document'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotFsmState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('telegram_user_id',),
            },
        ),
    ]
