# Generated by Django 5.2.15 on 2026-06-19 13:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot2', '0013_bot_fsm_state'),
        ('catalog', '0007_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentroster',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentroster',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='studentroster',
            name='course_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-4 for active students, 5 for graduated; null if not yet known', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentroster',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roster_programs', to='catalog.catalogitem'),
        ),
    ]
