# Generated by Django 5.2.15 on 2026-06-19 13:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot2', '0014_roster_optional_program_add_names'),
        ('catalog', '0007_auto'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bot2surveyresponse',
            name='survey_course_year_between_1_and_5',
        ),
        migrations.AlterField(
            model_name='bot2surveyresponse',
            name='course_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-4 for active students, 5 for graduated; null if not collected', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='bot2surveyresponse',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bot2_program_surveys', to='catalog.catalogitem'),
        ),
        migrations.AddConstraint(
            model_name='bot2surveyresponse',
            constraint=models.CheckConstraint(condition=models.Q(('course_year__isnull', True), models.Q(('course_year__gte', 1), ('course_year__lte', 5)), _connector='OR'), name='survey_course_year_between_1_and_5'),
        ),
    ]
