# Generated by Django 5.2.15 on 2026-06-25 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.utils import timezone


def backfill_accounts(apps, schema_editor):
    """Create one Bot2StudentAccount per existing student that already has a linked
    Telegram account, preserving its phone/username/name snapshot."""
    Bot2Student = apps.get_model('bot2', 'Bot2Student')
    Bot2StudentAccount = apps.get_model('bot2', 'Bot2StudentAccount')
    now = timezone.now()
    rows = []
    for s in Bot2Student.objects.exclude(telegram_user_id__isnull=True).iterator():
        rows.append(Bot2StudentAccount(
            student_id=s.id,
            telegram_user_id=s.telegram_user_id,
            username=s.username or "",
            first_name=s.first_name or "",
            last_name=s.last_name or "",
            phone=s.phone or "",
            is_active=True,
            last_seen_at=now,
        ))
    Bot2StudentAccount.objects.bulk_create(rows, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bot2', '0015_survey_nullable_program_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot2student',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='Bot2StudentAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='bot2.bot2student')),
            ],
            options={
                'ordering': ('-last_seen_at', '-created_at'),
                'indexes': [models.Index(fields=['student', 'is_active'], name='bot2_bot2st_student_4418fb_idx')],
            },
        ),
        migrations.RunPython(backfill_accounts, noop_reverse),
    ]
