# Generated by Django 5.2.15 on 2026-06-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot2', '0017_backfill_student_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot2document',
            name='doc_type',
            field=models.CharField(choices=[('cv', 'CV'), ('certificate', 'Certificate'), ('employment', "Ish joyi ma'lumotnomasi")], max_length=20),
        ),
    ]
