# Generated by Django 5.2.15 on 2026-06-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot2', '0018_alter_bot2document_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot2student',
            name='ai_skills',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bot2student',
            name='ai_skills_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
