# Generated by Django 5.2.13 on 2026-06-18 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='employers/')),
                ('description', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('mou_status', models.CharField(choices=[('negotiating', 'Negotiating'), ('signed', 'Signed'), ('expired', 'Expired')], default='negotiating', max_length=12)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.catalogitem')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['mou_status'], name='employers_e_mou_sta_c8ba35_idx'), models.Index(fields=['industry'], name='employers_e_industr_8f2f9c_idx')],
            },
        ),
    ]
