# Generated by Django 5.2.15 on 2026-06-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_auto'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employer',
            name='employers_e_industr_8f2f9c_idx',
        ),
        migrations.AlterField(
            model_name='employer',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
