PROMPTS = {
    # Uzbek
    "uz": {
        "ask_language": "Tilni tanlang / Выберите язык / Choose language:",
        "ask_contact": "Kontaktingizni ulashing:",
        "contact_button": "📱 Kontaktni ulashish",
        "ask_first": "Ismingizni kiriting:",
        "ask_last": "Familiyangizni kiriting:",
        "ask_gender": "Jinsingizni tanlang:",
        "gender_male": "👨 Erkak",
        "gender_female": "👩 Ayol",
        "ask_region": "Hududingizni tanlang:",
        "ask_student_id": "Student ID raqamingizni kiriting:",
        "ask_program": "Ta'lim yo'nalishingizni tanlang:",
        "ask_course_year": "Nechinchi kursda o'qiysiz?",
        "graduated": "🎓 Bitirganman",
        "course_year_label": "{year}-kurs",
        "ask_employment": "Hozirda ishlaysizmi?",
        "yes": "✅ Ha",
        "no": "❌ Yo'q",
        "ask_company": "Qaysi kompaniyada ishlaysiz?",
        "ask_role": "Qaysi lavozimda ishlaysiz?",
        "ask_help": "Universitet sizga ish topishda yordam bersinmi?",
        "ask_share": "Ma'lumotlaringizni ish beruvchilarga ulashishni istaysizmi?",
        "channels": "Quyidagi kanallarga a'zo bo'ling va xabardor bo'ling:",
        "ask_suggestions": "Universitet faoliyatini takomillashtirish bo'yicha takliflaringiz:",
        "thanks": "Rahmat! Ma'lumotlaringiz qabul qilindi. ✅",
        "submission_failed": "Ma'lumotlarni yuborishda xatolik yuz berdi. Javoblaringiz saqlanib qoldi — qayta yuborish uchun /retry buyrug'ini bosing.",
        "student_id_required": "Iltimos, Student ID raqamingizni matn ko'rinishida kiriting.",
        "use_buttons": "Iltimos, yuqoridagi tugmalardan birini tanlang.",
        "cancelled": "So'rovnoma bekor qilindi. Qaytadan boshlash uchun /start buyrug'ini bosing.",
        "unknown_command": "So'rovnomani boshlash uchun /start buyrug'ini bosing.",
        "retry_nothing": "Qayta yuboriladigan ma'lumot topilmadi. /start bilan boshlang.",
    },
    # Russian
    "ru": {
        "ask_language": "Tilni tanlang / Выберите язык / Choose language:",
        "ask_contact": "Поделитесь своим контактом:",
        "contact_button": "📱 Поделиться контактом",
        "ask_first": "Введите ваше имя:",
        "ask_last": "Введите вашу фамилию:",
        "ask_gender": "Выберите ваш пол:",
        "gender_male": "👨 Мужской",
        "gender_female": "👩 Женский",
        "ask_region": "Выберите ваш регион:",
        "ask_student_id": "Введите ваш Student ID:",
        "ask_program": "Выберите направление обучения:",
        "ask_course_year": "На каком вы курсе?",
        "graduated": "🎓 Выпускник",
        "course_year_label": "{year} курс",
        "ask_employment": "Вы сейчас работаете?",
        "yes": "✅ Да",
        "no": "❌ Нет",
        "ask_company": "В какой компании вы работаете?",
        "ask_role": "На какой должности вы работаете?",
        "ask_help": "Хотите, чтобы университет помог вам найти работу?",
        "ask_share": "Хотите ли вы поделиться своими данными с работодателями?",
        "channels": "Подпишитесь на следующие каналы, чтобы быть в курсе:",
        "ask_suggestions": "Ваши предложения по улучшению деятельности университета:",
        "thanks": "Спасибо! Ваши данные приняты. ✅",
        "submission_failed": "Произошла ошибка при отправке данных. Ваши ответы сохранены — нажмите /retry, чтобы повторить отправку.",
        "student_id_required": "Пожалуйста, введите ваш Student ID текстом.",
        "use_buttons": "Пожалуйста, выберите один из вариантов на кнопках выше.",
        "cancelled": "Опрос отменён. Нажмите /start, чтобы начать заново.",
        "unknown_command": "Нажмите /start, чтобы начать опрос.",
        "retry_nothing": "Нет данных для повторной отправки. Начните с /start.",
    },
    # English
    "en": {
        "ask_language": "Tilni tanlang / Выберите язык / Choose language:",
        "ask_contact": "Share your contact:",
        "contact_button": "📱 Share Contact",
        "ask_first": "Enter your first name:",
        "ask_last": "Enter your last name:",
        "ask_gender": "Select your gender:",
        "gender_male": "👨 Male",
        "gender_female": "👩 Female",
        "ask_region": "Select your region:",
        "ask_student_id": "Enter your Student ID:",
        "ask_program": "Select your education program:",
        "ask_course_year": "Which course year are you in?",
        "graduated": "🎓 Graduated",
        "course_year_label": "Year {year}",
        "ask_employment": "Are you currently employed?",
        "yes": "✅ Yes",
        "no": "❌ No",
        "ask_company": "Which company do you work for?",
        "ask_role": "What is your position?",
        "ask_help": "Would you like the university to help you find a job?",
        "ask_share": "Would you like to share your information with employers?",
        "channels": "Join the following channels to stay informed:",
        "ask_suggestions": "Your suggestions for improving university activities:",
        "thanks": "Thank you! Your information has been received. ✅",
        "submission_failed": "An error occurred while submitting. Your answers were saved — press /retry to resend.",
        "student_id_required": "Please enter your Student ID as text.",
        "use_buttons": "Please choose one of the buttons above.",
        "cancelled": "Survey cancelled. Press /start to begin again.",
        "unknown_command": "Press /start to begin the survey.",
        "retry_nothing": "Nothing to resubmit. Start with /start.",
    },
}

# Regions with translations
REGIONS = {
    "uz": [
        {"id": 1, "code": "tashkent_city", "name": "Toshkent shahri"},
        {"id": 2, "code": "tashkent_region", "name": "Toshkent viloyati"},
        {"id": 3, "code": "andijan", "name": "Andijon viloyati"},
        {"id": 4, "code": "bukhara", "name": "Buxoro viloyati"},
        {"id": 5, "code": "fergana", "name": "Farg'ona viloyati"},
        {"id": 6, "code": "jizzakh", "name": "Jizzax viloyati"},
        {"id": 7, "code": "namangan", "name": "Namangan viloyati"},
        {"id": 8, "code": "navoi", "name": "Navoiy viloyati"},
        {"id": 9, "code": "kashkadarya", "name": "Qashqadaryo viloyati"},
        {"id": 10, "code": "samarkand", "name": "Samarqand viloyati"},
        {"id": 11, "code": "surkhandarya", "name": "Surxondaryo viloyati"},
        {"id": 12, "code": "syrdarya", "name": "Sirdaryo viloyati"},
        {"id": 13, "code": "khorezm", "name": "Xorazm viloyati"},
        {"id": 14, "code": "karakalpakstan", "name": "Qoraqalpog'iston Respublikasi"},
    ],
    "ru": [
        {"id": 1, "code": "tashkent_city", "name": "город Ташкент"},
        {"id": 2, "code": "tashkent_region", "name": "Ташкентская область"},
        {"id": 3, "code": "andijan", "name": "Андижанская область"},
        {"id": 4, "code": "bukhara", "name": "Бухарская область"},
        {"id": 5, "code": "fergana", "name": "Ферганская область"},
        {"id": 6, "code": "jizzakh", "name": "Джизакская область"},
        {"id": 7, "code": "namangan", "name": "Наманганская область"},
        {"id": 8, "code": "navoi", "name": "Навоийская область"},
        {"id": 9, "code": "kashkadarya", "name": "Кашкадарьинская область"},
        {"id": 10, "code": "samarkand", "name": "Самаркандская область"},
        {"id": 11, "code": "surkhandarya", "name": "Сурхандарьинская область"},
        {"id": 12, "code": "syrdarya", "name": "Сырдарьинская область"},
        {"id": 13, "code": "khorezm", "name": "Хорезмская область"},
        {"id": 14, "code": "karakalpakstan", "name": "Республика Каракалпакстан"},
    ],
    "en": [
        {"id": 1, "code": "tashkent_city", "name": "Tashkent City"},
        {"id": 2, "code": "tashkent_region", "name": "Tashkent Region"},
        {"id": 3, "code": "andijan", "name": "Andijan Region"},
        {"id": 4, "code": "bukhara", "name": "Bukhara Region"},
        {"id": 5, "code": "fergana", "name": "Fergana Region"},
        {"id": 6, "code": "jizzakh", "name": "Jizzakh Region"},
        {"id": 7, "code": "namangan", "name": "Namangan Region"},
        {"id": 8, "code": "navoi", "name": "Navoi Region"},
        {"id": 9, "code": "kashkadarya", "name": "Kashkadarya Region"},
        {"id": 10, "code": "samarkand", "name": "Samarkand Region"},
        {"id": 11, "code": "surkhandarya", "name": "Surkhandarya Region"},
        {"id": 12, "code": "syrdarya", "name": "Syrdarya Region"},
        {"id": 13, "code": "khorezm", "name": "Khorezm Region"},
        {"id": 14, "code": "karakalpakstan", "name": "Republic of Karakalpakstan"},
    ],
}

# Channel links for subscription
CHANNELS = [
    {"name": "TTPU Career Center", "url": "https://t.me/+JCloQxJacT5lMjRi"},
    # {"name": "TTPU Jobs", "url": "https://t.me/ttpu_jobs"},
    # {"name": "TTPU Alumni", "url": "https://t.me/ttpu_alumni"},
]


def get_text(key: str, lang: str = "uz") -> str:
    """Get localized text by key and language."""
    return PROMPTS.get(lang, PROMPTS["uz"]).get(key, PROMPTS["uz"].get(key, key))


def get_regions(lang: str = "uz") -> list:
    """Get regions list for the specified language."""
    return REGIONS.get(lang, REGIONS["uz"])
