# Generated by Django 5.2.14 on 2026-05-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_drop_bot1_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetoken',
            name='service_name',
            field=models.CharField(choices=[('bot2', 'Bot2'), ('dashboard', 'Dashboard'), ('other', 'Other')], max_length=50),
        ),
    ]
